### ISSUE TITLE
can't connect to camera

### ISSUE THREAD

**Issue by stanos4** [sonyxperiadev/device-sony-kugo#20]
hello, i can't run camera app on my x compact with 7.0 build (repo synced today). Starting camera app shows only black screen and after ~minute it shows error message "can't connect to the camera" and crashes. I've got no clue what could be going on, here's at least my dmesg log from when I started camera app through adb till it crashes. Thank you for suggestions/help

[camera-log.txt](https://github.com/sonyxperiadev/device-sony-kugo/files/747683/camera-log.txt)

**Comment by jerpelea** [comment]
issue has been fixed
