### ISSUE TITLE
Front camera not work

### ISSUE THREAD

**Issue by DevriesL** [sonyxperiadev/device-sony-kugo#4]
Hello, my front camera not work in aosp with build guide in developer.sonymobile.com, could you please help me?
the kmsg error log is:
<3>[ 2346.137174]  msm_csid_init: Failed in getting TOP gdscr regulator handle
<3>[ 2346.215181]  msm_cci_init: Failed in getting TOP gdscr regulator handle<6>
[ 2346.222879] msm_cci_init:1310: hw_version = 0x10030000
<3>[ 2346.377391] msm_actuator_park_lens:1062 msm_actuator_park_lens:1062 Failed
 to park lens.
<3>[ 2346.385351] msm_actuator_power_down:1361 msm_actuator_power_down:1361 Lens
 park failed.
and the logcat is:
10-30 01:29:51.092   457 12272 E mm-camera-sensor: actuator_load_lib:516name=bu6
4747gwz
10-30 01:29:51.092   457 12272 I mm-camera-sensor: actuator_load_lib:563library
/system/vendor/lib/libactuator_bu64747gwz.so successfully loaded
10-30 01:29:51.093   457 12272 I mm-camera: sensor_get_fast_aec_wait_frames:1532
exit: wait_frame_count 0
10-30 01:29:51.093   457 12272 I mm-camera-sensor: module_sensor_offload_init_co
nfig:199Success
10-30 01:29:51.093   457 12272 E mm-camera-sensor: sensor_process_thread_message
:105sensor_process_thread_message: task took 36 ms
10-30 01:29:51.093   457   457 I mm-camera: sensor_get_cur_chromatix_name:2466ha
l version 0 capture intent 0 cur_stream_mask 1
10-30 01:29:51.093   457   457 E mm-camera: sensor_get_cur_chromatix_name:2516Er
ror: Load default preview chroamtix
10-30 01:29:51.093   457   457 I mm-camera: sensor_get_cur_chromatix_name:2522ch
romatix_lib_name[0] = libchromatix_imx300_preview.so
10-30 01:29:51.093   457   457 I mm-camera: sensor_get_cur_chromatix_name:2522ch
romatix_lib_name[1] = libchromatix_imx300_preview.so
10-30 01:29:51.093   457   457 I mm-camera: sensor_get_cur_chromatix_name:2523ch
romatix_lib_name[2] = NULL
10-30 01:29:51.093   457   457 I mm-camera: sensor_get_cur_chromatix_name:2522ch
romatix_lib_name[3] = libchromatix_imx300_common.so
10-30 01:29:51.093   457   457 I mm-camera: sensor_get_cur_chromatix_name:2522ch
romatix_lib_name[4] = libchromatix_imx300_cpp_preview.so
10-30 01:29:51.093   457   457 I mm-camera: sensor_get_cur_chromatix_name:2522ch
romatix_lib_name[5] = libchromatix_imx300_cpp_preview.so
10-30 01:29:51.093   457   457 I mm-camera: sensor_get_cur_chromatix_name:2522ch
romatix_lib_name[6] = libchromatix_imx300_cpp_preview.so
10-30 01:29:51.093   457   457 I mm-camera: sensor_get_cur_chromatix_name:2523ch
romatix_lib_name[7] = NULL
10-30 01:29:51.093   457   457 I mm-camera: sensor_get_cur_chromatix_name:2523ch
romatix_lib_name[8] = NULL
10-30 01:29:51.093   457   457 I mm-camera: sensor_get_cur_chromatix_name:2522ch
romatix_lib_name[9] = libchromatix_imx300_cpp_preview.so
10-30 01:29:51.093   457   457 I mm-camera: sensor_get_cur_chromatix_name:2522ch
romatix_lib_name[10] = libchromatix_imx300_postproc.so
10-30 01:29:51.093   457   457 I mm-camera: sensor_get_cur_chromatix_name:2522ch
romatix_lib_name[11] = libchromatix_imx300_default_preview_bu64747gwz.so
10-30 01:29:51.093   457   457 E mm-camera-isp2: isp_resource_query_mod:145 num_
isp_preallocate 2 num_session_opened 1 dual_vfe_enabled 0
10-30 01:29:51.094   457   457 E AEC_PORT: aec_port_query_capabilities:186  Get
AEC version function not implemented
10-30 01:29:51.094   457   457 D mm-camera: feature_mask 0xc9e hw version 0x4003
0000 max_pixel_bandwidth 680000000
10-30 01:29:51.094   457   457 E mm-camera: module_faceproc_query_mod:1924] Caps
 ROI 5 scene_mode_cnt 1 HW analysis supported 0
10-30 01:29:51.094   457   457 E hdr     : module_hdr_lib_query_mod:181] Support
ed scenemode cnt 2
10-30 01:29:51.094   457   457 I mm-camera: module_module_set_session_data:5632m
ax delay 2 report delay 1 retry skip 0
10-30 01:29:51.095   457   457 E AEC_PORT: aec_port_set_session_data:281  3A VER
SION --> 5.0.0.r2
10-30 01:29:51.100   457   457 E mm-camera-CORE: af_alg_DCIAF_create:2052  Creat
ion Successful
10-30 01:29:51.103   443  2714 E QCameraThermalAdapter: int qcamera::QCameraTher
malAdapter::init(qcamera::QCameraThermalCallback_): dlopen failed with error dlo
pen failed: library "/vendor/lib/libthermalclient.so" not found
10-30 01:29:51.103   443  2714 E QCamera2HWI: Init thermal adapter failed
10-30 01:29:51.103   443  2714 I QCamera2HWI: [KPI Perf] int qcamera::QCamera2Ha
rdwareInterface::openCamera(hw_device_t__): X PROFILE_OPEN_CAMERA camera id 0, r
c: 0
10-30 01:29:51.105   457 12285 D mm-camera: mct: mct_pipeline_start_stream_inter
nal: Adding session stream streamid= 0xf for session=1
10-30 01:29:51.105   457 12285 D mm-camera: mct: mct_pipeline_start_stream_inter
nal:Linking session stream for session 1
10-30 01:29:51.105   457 12285 D mm-camera: mct: mct_stream_start_link: Start li
nking Session-stream 0x1000f
10-30 01:29:51.105   457 12285 I mm-camera-sensor: port_sensor_caps_reserve:151i
de 1000f stream type 9 w_h 0_0
10-30 01:29:51.106   457 12285 I mm-camera-sensor: port_sensor_ext_link_func:281
ide 1000f
10-30 01:29:51.106   457 12285 E mm-camera-isp2: isp_port_check_caps_reserve:731
 port 0xf4db67c0 ide 1000f type 9 dim 0 0
10-30 01:29:51.107   443 12269 D QCameraParameters: int32_t qcamera::QCameraPara
meters::setSecureMode(const char_): Secure mode value: disable
10-30 01:29:51.108   457 12285 E mm-camera: int_link = 0xf421e000
10-30 01:29:51.108   457 12285 D mm-camera: pproc_port_add_modules_to_stream:434
, LINK linking mods tmod and c2d for identity 1000f
10-30 01:29:51.108   457 12285 D mm-camera: c2d_port_check_caps_reserve:78, iden
tity=0x1000f
10-30 01:29:51.108   457 12285 D mm-camera: c2d_port_check_caps_reserve:156, ide
ntity=0x1000f, reserved
10-30 01:29:51.108   457 12285 D mm-camera: c2d_module_notify_add_stream:1464, i
nfo: success, identity=0x1000f
10-30 01:29:51.109   457 12285 D mm-camera: pproc_port_add_modules_to_stream:434
, LINK linking mods c2d and cpp for identity 1000f
10-30 01:29:51.109   457 12285 D mm-camera: c2d_port_check_caps_reserve:78, iden
tity=0x1000f
10-30 01:29:51.109   457 12285 E mm-camera: Interleaved flag is 0, identity 6555
1 port type 0
10-30 01:29:51.110   457 12285 D mm-camera: c2d_port_check_caps_reserve:156, ide
ntity=0x1000f, reserved
10-30 01:29:51.110   457 12285 D mm-camera: cpp_port_check_caps_reserve:137, ide
ntity=0x1000f, reserved
10-30 01:29:51.110   457 12285 D mm-camera: cpp_module_notify_add_stream:2131, i
nfo: success, identity=0x1000f
10-30 01:29:51.110   457 12285 D mm-camera: pproc_port_add_modules_to_stream:434
, LINK linking mods cpp and afs for identity 1000f
10-30 01:29:51.110   457 12285 D mm-camera: cpp_port_check_caps_reserve:137, ide
ntity=0x1000f, reserved
10-30 01:29:51.110   457 12285 D mm-camera: pproc_port_add_modules_to_stream:434
, LINK linking mods afs and ezt for identity 1000f
10-30 01:29:51.110   457 12285 E mm-camera: pproc_port_add_modules_to_stream:455
] X rc: 1
10-30 01:29:51.112   457 12285 D mm-camera: mct: mct_pipeline_start_stream_inter
nal:Session stream linked successfully session 1
10-30 01:29:51.113   457 12286 D mm-camera: cpp_module_set_parm_effect:2055] ide
n:0x1000f effect:1
10-30 01:29:51.114   457 12286 E mm-camera: iface_util_set_hfr: can't find hw st
ream, only save hfr mode
10-30 01:29:51.120  8779  8779 E Camera-JNI: android_hardware_Camera_getCameraIn
fo: Unknown camera ID 1
10-30 01:29:51.130  8779  8779 I Choreographer: Skipped 32 frames!  The applicat
ion may be doing too much work on its main thread.
10-30 01:29:51.185   443  2157 I QCamera2HWI: [KPI Perf] static void qcamera::QC
amera2HardwareInterface::stop_preview(camera_device_): E PROFILE_STOP_PREVIEW ca
mera id 0
10-30 01:29:51.186   443  2157 I QCamera2HWI: [KPI Perf] static void qcamera::QC
amera2HardwareInterface::stop_preview(camera_device_): X
10-30 01:29:51.190   443   443 I QCamera2HWI: [KPI Perf] static void qcamera::QC
amera2HardwareInterface::stop_preview(camera_device_): E PROFILE_STOP_PREVIEW ca
mera id 0
10-30 01:29:51.191   443   443 I QCamera2HWI: [KPI Perf] static void qcamera::QC
amera2HardwareInterface::stop_preview(camera_device_): X
10-30 01:29:51.191   443   443 I CameraFlashlight: Destroying camera 0
10-30 01:29:51.191   443   443 I QCamera2HWI: [KPI Perf] static int qcamera::QCa
mera2HardwareInterface::close_camera_device(hw_device_t*): E camera id 0
10-30 01:29:51.192   443   443 I QCamera2HWI: [KPI Perf] int qcamera::QCamera2Ha
rdwareInterface::closeCamera(): E PROFILE_CLOSE_CAMERA camera id 0
10-30 01:29:51.193   457 12286 I mm-camera: sensor_get_output_info:4002requested
 dim 0 0 stream mask 0
10-30 01:29:51.193   457 12286 E mm-camera-sensor: sensor_pick_fill_expected_dat
a:397ex_w:0, ex_h:0,ex_mode:1, ex_fps:30.000000, ex_clk:0, ex_ar: 0
10-30 01:29:51.193   457 12286 I mm-camera-sensor: sensor_pick_resolution:590res
_idx: 1
10-30 01:29:51.193   457 12286 I mm-camera: sensor_get_output_info:4031pick res
1 dim 3864X2176 op clk 464000000
10-30 01:29:51.193   457 12286 E mm-camera: isp_util_print_meta_stream_info:5539
 Deallocate resources
10-30 01:29:51.194   457 12286 E mm-camera: mct: mct_pipeline_unmap_buf: Un-Mapp
ing failed for sync buf
10-30 01:29:51.194   457 12286 E mm-camera: mct: mct_pipeline_unmap_buf: pipelin
e sanity failed
10-30 01:29:51.195   443   443 E QCamera2HWI: int32_t qcamera::QCamera2HardwareI
nterface::waitDeferredWork(uint32_t&): Invalid job id 0
10-30 01:29:51.195   443   443 E QCamera2HWI: int32_t qcamera::QCamera2HardwareI
nterface::waitDeferredWork(uint32_t&): Invalid job id 0
10-30 01:29:51.196   457 12286 D mm-camera: mct: mct_pipeline_process_set:comman
d=800000b
10-30 01:29:51.196   457 12286 E mm-camera: mct: mct_pipeline_process_set:2524:
Couldn't find stream id: 0
10-30 01:29:51.196   457   457 D mm-camera: mct: mct_controller_destroy: Initiat
ing destroy sequence
10-30 01:29:51.197   457   457 D mm-camera: mct: mct_controller_destroy: serv_th
read closed
10-30 01:29:51.197   457 12288 D mm-camera: mct: mct_bus_handler_thread_run: For
ce Exit
10-30 01:29:51.197   457   457 D mm-camera: mct: mct_controller_destroy: bus_han
dler thread closed
10-30 01:29:51.197   457   457 D mm-camera: mct: mct_pipeline_stop_session - E
10-30 01:29:51.197   457   457 D mm-camera: mct: mct_pipeline_process_set:comman
d=800000b
10-30 01:29:51.198   457   457 D mm-camera: mct: mct_pipeline_process_set: Issui
ng DEL_STREAM on stream 0x1000f and stream type=9
10-30 01:29:51.198   457   457 I mm-camera-sensor: port_sensor_unlink_func:303id
e 1000f
10-30 01:29:51.198   457   457 E mm-camera: port_iface_ext_unlink_func: E, ident
ity = 0x1000f, port = 0xf4eed2c0, direction = 2
10-30 01:29:51.198   457   457 I mm-camera-sensor: port_sensor_caps_unreserve:21
4ide 1000f
10-30 01:29:51.198   457   457 E mm-camera: port_iface_check_caps_unreserve_func
:  E, identity = 0x1000f, port = 0xf4eed2c0, direction = 2
10-30 01:29:51.198   457   457 E mm-camera: iface_unreserve_sink_port: stream_id
 f mode 0
10-30 01:29:51.198   457   457 E mm-camera: port_iface_ext_unlink_func: E, ident
ity = 0x1000f, port = 0xf4eedcc0, direction = 1
10-30 01:29:51.198   457   457 E mm-camera: iface_ext_unlink_src_port: mct strea
m already removed from hw stream
10-30 01:29:51.198   457   457 E mm-camera: port_iface_check_caps_unreserve_func
:  E, identity = 0x1000f, port = 0xf4eedcc0, direction = 1
10-30 01:29:51.198   457   457 E mm-camera-isp2: isp_port_check_caps_unreserve:8
20 ide 1000f port 0xf4db67c0
10-30 01:29:51.198   457   457 D mm-camera: c2d_port_check_caps_unreserve:183, i
dentity=0x1000f
10-30 01:29:51.198   457   457 D mm-camera: c2d_port_check_caps_unreserve:193, i
dentity=0x1000f, unreserved
10-30 01:29:51.198   457   457 D mm-camera: c2d_port_check_caps_unreserve:183, i
dentity=0x1000f
10-30 01:29:51.198   457   457 D mm-camera: c2d_port_check_caps_unreserve:193, i
dentity=0x1000f, unreserved
10-30 01:29:51.198   457   457 D mm-camera: cpp_port_check_caps_unreserve:164, i
dentity=0x1000f
10-30 01:29:51.198   457   457 D mm-camera: cpp_port_check_caps_unreserve:174, i
dentity=0x1000f, unreserved
10-30 01:29:51.198   457   457 D mm-camera: cpp_port_check_caps_unreserve:164, i
dentity=0x1000f
10-30 01:29:51.198   457   457 D mm-camera: cpp_port_check_caps_unreserve:174, i
dentity=0x1000f, unreserved
10-30 01:29:51.201   457   457 D mm-camera: mct: mct_pipeline_process_set: Strea
m 0x1000f and stream type=9, successfully deleted
10-30 01:29:51.201   457   457 E mm-camera: mct: mct_pipeline_stop_stream_intern
al stream unmap_parm failed
10-30 01:29:51.201   457 12297 I mm-camera: module_sensor_stop_session:1137sessi
on 1
10-30 01:29:51.205   457 12299 E mm-camera-isp2: isp_module_stop_session:456 ses
sion id 1
10-30 01:29:51.208   457 12301 D mm-camera: cpp_module_stop_session:562, info: s
topping session 1 ...
10-30 01:29:51.208   457 12282 D mm-camera: cpp_thread_process_pipe_message:652,
 CPP_THREAD_MSG_ABORT: cpp_thread exiting..
10-30 01:29:51.208   457   457 D mm-camera: mct: mct_pipeline_stop_session: left
 modules: 5
10-30 01:29:51.208   457   457 D mm-camera: mct: mct_pipeline_stop_session: left
 modules: 4
10-30 01:29:51.208   457 12302 E mm-camera: module_faceproc_stop_session:1812] s
ession cnt 1
10-30 01:29:51.212   457   457 D mm-camera: mct: mct_pipeline_stop_session: left
 modules: 3
10-30 01:29:51.213   457 12301 D mm-camera: cpp_module_stop_session:611, info: s
ession 1 stopped.
10-30 01:29:51.213   457 12301 D mm-camera: c2d_module_stop_session:385, info: s
topping session 1 ...
10-30 01:29:51.213   457 12283 D mm-camera: c2d_thread_process_pipe_message:844,
 C2D_THREAD_MSG_ABORT: c2d_thread exiting..
10-30 01:29:51.213   457 12301 D mm-camera: c2d_module_stop_session:430, info: s
ession 1 stopped.
10-30 01:29:51.213   457 12301 E mm-camera-pp: [INFO] base_module_stop_session:9
8, E, session=1
10-30 01:29:51.214   457 12301 E mm-camera-eztune: [INFO] eztune_module_stop_ses
sion:49, E, session=1
10-30 01:29:51.215   457   457 D mm-camera: mct: mct_pipeline_stop_session: left
 modules: 2
10-30 01:29:51.216   457   457 D mm-camera: mct: mct_pipeline_stop_session: left
 modules: 1
10-30 01:29:51.366   457 12272 I mm-camera-sensor: sensor_thread_func:155sensor_
thread_func:Sensor thread is exiting
10-30 01:29:51.367   457   457 D mm-camera: mct: mct_pipeline_stop_session: left
 modules: 0
10-30 01:29:51.367   457   457 D mm-camera: mct: mct_pipeline_stop_session - X
10-30 01:29:51.367   457   457 D mm-camera: mct: mct_pipeline_destroy E: session
:1
10-30 01:29:51.367   457   457 D mm-camera: mct: mct_pipeline_destroy X: Pipelin
e destroyed successfully
10-30 01:29:51.367   457   457 D mm-camera: mct: mct_controller_destroy: X Succe
ssfully closed mct_controller

**Comment by jerpelea** [comment]
issue has been fixed
