### ISSUE TITLE
If SW_binaries equals vendor?

### ISSUE THREAD

**Issue by qinyj12** [sonyxperiadev/device-sony-kugo#51]
Hi friends. 
I really want to know , if SW_binaries_for_Xperia_Android equals the file named ODM? Is it has anotner name called vendor? 
When I flash Omni rom and AOSP, I was asked to flash SW_binaries additionally.
When I try to build Lineage or other rom, I was asked to provide vendor.
So I wonder if they are the same thing. 
If so, can I build Lineage rom without vendor?For I can flash vendor additionally after flashing Lineage.
Or do I need to write some code to extract vendor from my device?
thanks! hope your reply.

**Comment by Paulbouchara** [comment]
Hey, you should write your issue in the bugtracker next time :)

Anyway simple answer:
the vendor asked in lineage build is not necessary, you would need only the SOD device trees (+ all the stuff that comes with the local_manifest repo (android-8.1.0_r3 should be fine)) and an adapted lineage.mk file (take exemple from exisitng devices and replace it by sony values according to your device) to build correctly.
Oh and make sure you apply the patches needed to make android load the ODM partition (found in repo_update.sh (in the same name repo))

Once you successfully build your image, flash it, make sure you flashed the ODM and enjoy :)

**Comment by qinyj12** [comment]
oops, sorry for that.I will close this issue and try your method. thank you! thanks for your reply!
